### ISSUE TITLE
Bug in your MSSSIM implementation

### ISSUE THREAD

**Issue by ductm104** [jorge-pessoa/pytorch-msssim#13]
From Tensorflow implementation [line 182](https://github.com/tensorflow/models/blob/563d923a0822cd99930c17108b177c9ab00f795e/research/compression/image_encoder/msssim.py#L182), I saw that they first apply an average pooling filter then downsample by slicing with step 2:
```python
for _ in range(levels):
    ssim, cs = _SSIMForMultiScale(...)
    ...
    filtered = [convolve(im, downsample_filter, mode='reflect')
                for im in [im1, im2]]
    im1, im2 = [x[:, ::2, ::2, :] for x in filtered]
```

But in your [implementation](https://github.com/jorge-pessoa/pytorch-msssim/blob/72028be705d3e350067df3cacd64e05f3b410f12/pytorch_msssim/__init__.py#L82), you only apply a 2x2 AvgPool, so the images are not downsampled by 2 as in the paper.
```python
for _ in range(levels):
    sim, cs = ssim(...)
    ...

    img1 = F.avg_pool2d(img1, (2, 2))
    img2 = F.avg_pool2d(img2, (2, 2))
```

**Comment by jorge-pessoa** [comment]
Hello,
Thank you for raising this point. Note that the avg_pool2d stride defaults to the kernel size (which is (2, 2)).

As far as I understand, from the original implementation of MS-SSIM:

```
downsample_filter = ones(2)./4;
(...)
for l = 1:level
  (...)
   filtered_im1 = imfilter(im1, downsample_filter, 'symmetric', 'same');
   filtered_im2 = imfilter(im2, downsample_filter, 'symmetric', 'same');
   clear im1, im2;
   im1 = filtered_im1(1:2:end, 1:2:end);
   im2 = filtered_im2(1:2:end, 1:2:end);
```

At each iteration, the image is averaged over a 2x2 window using the downsample_filter and then each odd value in width and height is kept using the range selection (every 2 values, so that no window overlaps). I believe this is the same behaviour as an avg_pool2d of kernel_size (2, 2) and stride (2, 2) as is used in the code. The tensorflow code provided seems to use the same logic as the original implementation. 

Please let me know if I understood your point incorrectly or misinterpreted the original implementation. Thank you for your contribution

**Comment by ductm104** [comment]
Sorry about not read the docs carefully. I checked the pytorch documents and your implementation is correct.

**Comment by jorge-pessoa** [comment]
No problem. Thank you for using the library, and feel free to open other issues if you have any more questions.

Closing this issue.
