### ISSUE TITLE
Is the threshold necessary?

### ISSUE THREAD

**Issue by chledowski** [jorge-pessoa/pytorch-msssim#14]
I have seen that you use `while value < threshold:` in your code - could you explain if it is necessary and why?

Thanks!

**Comment by jorge-pessoa** [comment]
Hello,

This threshold is only used for demonstration purposes in the provided demo script in order to stop the optimization procedure at a satisfactory MS-SSIM value for the reconstruction of the original image. As a regular use-case to train a neural network you would usually structure your optimization procedure differently and not use a threshold in this manner.
